In [1]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [2]:
x=[1,2,3,4]
y=np.array(x)
print(y)
print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
l=[]
for i in range(1,5):
    data=int(input("Enter data : "))
    l.append(data)
print(np.array(l))
print(np.array(l).ndim)

Enter data :  5
Enter data :  6
Enter data :  6
Enter data :  5


[5 6 6 5]
1


In [4]:
ar2=np.array([[2,3,4],[2,3,6]])
ar3=np.array([[[]]])
arn=np.array([[[[[[]]]]]])
print(ar2)
print(ar2.ndim)
print(ar3.ndim)
print(arn.ndim)

[[2 3 4]
 [2 3 6]]
2
3
6
