**Zeros**

In [1]:
import numpy as np

arr_zero=np.zeros(4)
arr1_zero=np.zeros((2,3))

print(arr_zero)
print()
print(arr1_zero)

[0. 0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]


**Ones**

In [2]:
arr_one=np.ones(5)
print(arr_one)

[1. 1. 1. 1. 1.]


**Empty**

In [3]:
# arr_empty=np.empty(3)
# arr_empty=np.empty(4)
arr_empty=np.empty(5)
# priviously memory ke element empty array me aa jate hai
print(arr_empty)

[1. 1. 1. 1. 1.]


**Range**

In [4]:
arr_range=np.arange(4)
print(arr_range)

[0 1 2 3]


**diagonal element fill with 1's**

In [7]:
# arr_diagonal=np.eye(3)
arr_diagonal=np.eye(3,5)
print(arr_diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


**LinSpace**

In [6]:
arr_space=np.linspace(0,40,num=5)
print(arr_space)

[ 0. 10. 20. 30. 40.]
