**rand**

In [1]:
import numpy as np
var=np.random.rand(4)
print(var)

[0.99964855 0.20089991 0.54503916 0.31465116]


In [2]:
import numpy as np
var1=np.random.rand(3,5)
print(var1)

[[0.89383104 0.36513908 0.67723101 0.44806573 0.80927354]
 [0.85465338 0.46667668 0.74323128 0.03719623 0.79652708]
 [0.75496866 0.17428577 0.3529793  0.20107362 0.02234929]]


**randn**

In [3]:
var2=np.random.randn(5)
print(var2)

[-1.30799723  0.11760564  0.21328124  0.91140076 -1.30397033]


**ranf**

In [4]:
var3=np.random.ranf(5)
print(var3)

[0.17326752 0.96935827 0.7871179  0.62739292 0.62805819]


**randint**

In [5]:
# (min,max,total_value)
var4=np.random.randint(5,20,5)
print(var4)

[14 16 13 18 15]
