**dataType numpy array (search google)**

In [1]:
import numpy as np
var=np.array([1,2,3,4])
print("Data Type : ",var.dtype) 

Data Type :  int32


In [2]:
import numpy as np
var=np.array([1.2,2.0,3,4])
print("Data Type : ",var.dtype) 

Data Type :  float64


In [3]:
var=np.array(["A","B","C","D"])
print("Data Type : ",var.dtype) 

Data Type :  <U1


In [4]:
var=np.array(["A","B",3,4])
print("Data Type : ",var.dtype) 

Data Type :  <U11


In [5]:
x=np.array([1,2,3,4],dtype=np.int8)
print("Data Type : ",x.dtype) 
print(x)

Data Type :  int8
[1 2 3 4]


In [6]:
x1=np.array([1,2,3,4],dtype="f")
print("Data Type : ",x1.dtype) 
print(x1)

Data Type :  float32
[1. 2. 3. 4.]


In [7]:
x2=np.array([1,2,3,4])
new =np.float32(x2)
new2=np.int_(new)

print("Data Type : ",x2.dtype)
print("Data Type : ",new.dtype)
print("Data Type : ",new2.dtype)

print(x2)
print(new)
print(new2)

Data Type :  int32
Data Type :  float32
Data Type :  int32
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]
