In [1]:
import numpy as np
arr=np.array([[1,2,3],[1,2,3]])
print(arr)
print()
print(arr.shape)

[[1 2 3]
 [1 2 3]]

(2, 3)


In [2]:
arr1=np.array([1,2,3,4],ndmin=4)
print(arr1)
print(arr1.ndim)
print()
print(arr1.shape)

[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


***Reshape***

In [3]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
print(a.dtype)
print(a.ndim)

print()
x=a.reshape(2,5)
print(x)
print(x.dtype)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10]
int32
1

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
int32
2


In [4]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ar)
print(ar.ndim)

print()
x3=ar.reshape(2,3,2)
print(x3)
print(x3.ndim)

print()
one=x3.reshape(12)
print(one)
print(one.ndim)
print(one.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)
