In [1]:
import numpy as np
var=np.array([1,2,3,4])
varadd=var+3
print(varadd)

[4 5 6 7]


In [2]:

var=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
add=var+var2
print(add)

[2 4 6 8]


In [3]:
var=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
add=np.add(var,var2)
print(add)

[2 4 6 8]


In [4]:

var=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
sub=var-var2
print(sub)

[0 0 0 0]


In [5]:
var=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
sub=np.subtract(var,var2)
print(sub)

[0 0 0 0]


In [6]:

var=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
mul=var*var2
print(mul)

[ 1  4  9 16]


In [7]:

var=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
divide=var/var2
print(divide)

[1. 1. 1. 1.]


In [8]:
var=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
mod=var%3
print(mod)

[1 2 0 1]


In [9]:
var=np.array([1,2,3,4])
var2=np.array([1,2,3,4])
power=var**var2
print(power)

[  1   4  27 256]


In [10]:
var=np.array([1,2,3,4])
r=np.reciprocal(var)
print(r)

[1 0 0 0]


**2D Array**

In [11]:
var21=np.array([[1,2,3],[4,5,6]])
var22=np.array([[7,8,9],[0,0,0]])
print(var21)
print()
print(var22)
print()
result=np.add(var21,var22)
print(result)

[[1 2 3]
 [4 5 6]]

[[7 8 9]
 [0 0 0]]

[[ 8 10 12]
 [ 4  5  6]]


In [12]:
var21=np.array([[1,2,3],[4,5,6]])
var22=np.array([[7,8,9],[0,0,0]])
result=np.multiply(var21,var22)
print(result)

[[ 7 16 27]
 [ 0  0  0]]
