In [1]:
import numpy as np
arr=np.array([1,2,3,1,4])
print("min : ",np.min(arr),".....index number : ",np.argmin(arr))
print("max : ",np.max(arr),".....index number : ",np.argmax(arr))
print("sqrt : ",np.sqrt(arr))
print("sin value : ",np.sin(arr))
print("cos value : ",np.cos(arr))
print("cumsum : ",np.cumsum(arr))

min :  1 .....index number :  0
max :  4 .....index number :  4
sqrt :  [1.         1.41421356 1.73205081 1.         2.        ]
sin value :  [ 0.84147098  0.90929743  0.14112001  0.84147098 -0.7568025 ]
cos value :  [ 0.54030231 -0.41614684 -0.9899925   0.54030231 -0.65364362]
cumsum :  [ 1  3  6  7 11]


In [2]:
var1=np.array([[3,4,5,6],[5,7,9,54]])
print(var1)
print(np.min(var1,axis=1)) # axis=1 => row wise 
print()
print(var1)
print(np.min(var1,axis=0)) # axis=0 => col wise

[[ 3  4  5  6]
 [ 5  7  9 54]]
[3 5]

[[ 3  4  5  6]
 [ 5  7  9 54]]
[3 4 5 6]
