In [1]:
import numpy as np
var1=np.array([1,2,3])
print(var1.shape)
print(var1.ndim)
print(var1)
print()

var2=np.array([[1],[2],[3]])
print(var2.shape)
print(var2.ndim)
print(var2)
print()
print()
print("Addition")
print(np.add(var1,var2))

(3,)
1
[1 2 3]

(3, 1)
2
[[1]
 [2]
 [3]]


Addition
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [2]:
x=np.array([[2],[4]])
print(x.shape)
y=np.array([[2,3,4],[5,6,7]])
print(y.shape)
print()
print(np.add(x,y))

(2, 1)
(2, 3)

[[ 4  5  6]
 [ 9 10 11]]
