**Indexing**


In [1]:
import numpy as np
#          -4,-3,-2,-1
#           0, 1, 2, 3
x=np.array([1 ,2 ,3 ,4])
print(x[0])
print(x[-4])

1
1


In [2]:
y=np.array([[1,2,3],[1,2,3]])
print(y[0])
print(y[-2])
print(y[0][-2])
print(y[0][1])

[1 2 3]
[1 2 3]
2
2


In [3]:
z=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(z)
print()
print()
print(z[0])
print(z[-2])
print()
print()
print(z[0][1][-2])
print(z[-2][-1][1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


5
5


**slicing**

In [10]:
a=np.array([3,5,7,15,5,7,1,2,54])
print(a)
print()
print("2 to 5 :",a[1:4])
print("2 to End :",a[1:])
print("Start to 5 :",a[:5])
print("step : ",a[::2])
print("step : ",a[0:5:3])

[ 3  5  7 15  5  7  1  2 54]

2 to 5 : [ 5  7 15]
2 to End : [ 5  7 15  5  7  1  2 54]
Start to 5 : [ 3  5  7 15  5]
step :  [ 3  7  5  1 54]
step :  [ 3 15]


In [26]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("7 to 10 :",b[1,1:])
print("7 to 9 :",b[1,1:4])
print("print 15 13 11 :",b[-1,-1:-6:-2])

7 to 10 : [ 7  8  9 10]
7 to 9 : [7 8 9]
print 15 13 11 : [15 13 11]
