In [1]:
import numpy as np
arr=np.array([1,4,6,2,5])
print(arr)
print()
for i in arr:
    print(i)

print()
for i in np.nditer(arr):
    print(i)

[1 4 6 2 5]

1
4
6
2
5

1
4
6
2
5


In [2]:
for i in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(i)

b'1'
b'4'
b'6'
b'2'
b'5'


In [3]:
#i me indexing value
#d me data
for i,d in np.ndenumerate(arr):
    print(i,d)

(0,) 1
(1,) 4
(2,) 6
(3,) 2
(4,) 5


In [4]:
arr2=np.array([[2,3,4],[4,5,1]])
print(arr2)
print()
for i in arr2:
    print(i)
print()
for i in arr2:
    for j in i:
        print(j)


[[2 3 4]
 [4 5 1]]

[2 3 4]
[4 5 1]

2
3
4
4
5
1


In [5]:
print()
for i in np.nditer(arr2):
    print(i)


2
3
4
4
5
1


In [6]:
arr3=np.array([[[2,3,4,5],[4,5,1,5]]])
print(arr3)
print(arr3.ndim)
print()
for i in arr3:
    for j in i:
        for k in j:
            print(k)


[[[2 3 4 5]
  [4 5 1 5]]]
3

2
3
4
5
4
5
1
5


In [7]:
print()
for i in np.nditer(arr3,flags=['buffered'],op_dtypes=['S']):
    print(i)


b'2'
b'3'
b'4'
b'5'
b'4'
b'5'
b'1'
b'5'


In [8]:
#i me indexing value
#d me data
for i,d in np.ndenumerate(arr3):
    print(i,d)

(0, 0, 0) 2
(0, 0, 1) 3
(0, 0, 2) 4
(0, 0, 3) 5
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 1
(0, 1, 3) 5
