**Join**

In [1]:
import numpy as np
arr=np.array([1,2,3])
arr2=np.array([4,5,6])
join=np.concatenate((arr,arr2))
# join=np.concatenate((arr,arr2),axis=0)
# join=np.concatenate((arr,arr2),axis=1) # show error
print(join)


[1 2 3 4 5 6]


In [2]:
ar=np.array([[1,2],[3,4]])
ar2=np.array([[5,6],[7,8]])
join2=np.concatenate((ar,ar2))
# join2=np.concatenate((ar,ar2),axis=0) #col wise
# join2=np.concatenate((ar,ar2),axis=1) # wow wise
print(join2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
arr=np.array([[1,2,3],[1,2,3]])
arr2=np.array([[4,5,6],[4,5,6]])
stack_merge_arr_arr2=np.stack((arr,arr2))
axis_zero=np.stack((arr,arr2),axis=0) # work col's along 
col_vstack=np.vstack((arr,arr2)) # work vertical's along 
axis_one=np.stack((arr,arr2),axis=1) # work row's along 
col_dstack=np.hstack((arr,arr2)) # work horizontal's along 
height=np.dstack((arr,arr2)) # work height's along 
print(stack_merge_arr_arr2)
print()
print(axis_zero)
print()
print(col_vstack)
print()
print(axis_one)
print()
print(col_dstack)
print()
print(height)

[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]

[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]

[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]

[[[1 4]
  [2 5]
  [3 6]]

 [[1 4]
  [2 5]
  [3 6]]]


**spilit**


In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
spilit_arr=np.array_split(arr,3)
print(spilit_arr)
print(spilit_arr[0])

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [18]:
arr2=np.array([[1,2],[3,4],[5,6]])
print(arr2)
# spilit_arr2=np.array_split(arr2,3) 
spilit_arr2=np.array_split(arr2,3,axis=1)
print(spilit_arr2)
print()
print(spilit_arr2[0])

[[1 2]
 [3 4]
 [5 6]]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]

[[1]
 [3]
 [5]]
