**#Search**

In [1]:
import numpy as np
arr=np.array([2,3,5,1,43,7,43,7,6,9,35,7])
x=np.where(arr==7)
y=np.where(arr%2==0)
print(x)
print(y)

(array([ 5,  7, 11], dtype=int64),)
(array([0, 8], dtype=int64),)


**searchsorted**


In [2]:
arr2=np.array([1,2,3,4,6,8,9])
# x=np.searchsorted(arr2,7)
# x=np.searchsorted(arr2,7,side="right")
x=np.searchsorted(arr2,[5,6,7],side="right")
print(x)


[4 5 5]


**sort**


In [3]:
ar=np.array([2,3,5,1,43,7,73,17,6,9,35,11])
strarr=np.array(['a','r','c','b','p'])
print(np.sort(ar))
print(np.sort(strarr))

[ 1  2  3  5  6  7  9 11 17 35 43 73]
['a' 'b' 'c' 'p' 'r']


In [4]:
ar2=np.array([[2,3,5],[1,43,7],[73,17,6],[9,35,11]])
print(np.sort(ar2))

[[ 2  3  5]
 [ 1  7 43]
 [ 6 17 73]
 [ 9 11 35]]


**Filter Array**

In [5]:
arf=np.array(['a','r','c','b','p'])
f=[True,False,True,False,False]
newArf=arf[f]
print(newArf)
print(type(newArf))

['a' 'c']
<class 'numpy.ndarray'>
