**Shuffle**

In [1]:
import numpy as np
var=np.array([4,5,6,3,1])
np.random.shuffle(var)
print(var)

[5 1 3 6 4]


**unique**

In [5]:
var2=np.array([4,5,2,4,5,6,6,3,34,5,5,34,3])
# x=np.unique(var2,return_index=True,return_counts=True)
x=np.unique(var2)
print(x)

[ 2  3  4  5  6 34]


**resize & flatten & reval**

In [3]:
var3=np.array([4,5,6,3,4,1])
y=np.resize(var3,(2,3))
print(y)
print()
print(y.ndim)
print()
print("Flatten")
print(y.flatten()) # by default is C
print(y.flatten(order='C')) # 'C' means to flatten in row-major (C-style) order
print(y.flatten(order='F')) # 'F' means to flatten in column-major (Forten-style) order
print(y.flatten(order='A')) # 'A' means to flatten in column-major order if `a` is Forten *contiguous* in memory, row -major order otherwise.
print(y.flatten(order='K')) # 'K' means to flatte `a` in order the elements occur in memory
print("Reval")
print(np.ravel(y,order='A'))

[[4 5 6]
 [3 4 1]]

2

Flatten
[4 5 6 3 4 1]
[4 5 6 3 4 1]
[4 3 5 4 6 1]
[4 5 6 3 4 1]
[4 5 6 3 4 1]
Reval
[4 5 6 3 4 1]


In [4]:
var4=np.array([[4,5,2],[4,5,6],[6,3,34],[5,5,34]])
