In [1]:
import numpy as np
var=np.array([1,2,3,4,5])
print(var)
# accept only integer value (float convert into interger)
#            arr  index  value 
# v=np.insert(var,  2,    10)
# v=np.insert(var,(2,4),100)
v=np.append(var,1000)
print(v)

[1 2 3 4 5]
[   1    2    3    4    5 1000]


In [7]:
import numpy as np
var2=np.array([[1,2,3],[4,5,6]])
print(var2)
print()
# v2=np.insert(var2,2,[7,7,7],axis=0)
v2=np.append(var2,[[10,10,10]],axis=0)
print(v2)

[[1 2 3]
 [4 5 6]]

[[ 1  2  3]
 [ 4  5  6]
 [10 10 10]]


**Delete**

In [8]:
var=np.array([7,2,4,9,5])
print(var)
v=np.delete(var,3)
print(v)

[7 2 4 9 5]
[7 2 4 5]
