In [17]:
import numpy as np
m=np.matrix([[1,2],[4,5]])
m2=np.matrix([[1,2],[4,5]])
print(m)
print(m.dtype)
print(type(m))
print("Addition")
print(m+m2)
print("Subtraction")
print(m-m2)
print("Multiplication")
print(m*m2)
# print(m.dot(m2))

[[1 2]
 [4 5]]
int32
<class 'numpy.matrix'>
Addition
Subtraction
Multiplication
[[ 9 12 15]
 [24 33 42]]


In [15]:
a=np.array([[1,2,3],[4,5,6]])
a2=np.array([[1,2,3],[4,5,6]])
print(a)
print(m.dtype)
print(type(a))
print("Addition")
print(a+a2)
print("Subtraction")
print(a-a2)
print("Multiplication")
print(a*a2)

[[1 2 3]
 [4 5 6]]
int32
<class 'numpy.ndarray'>
Addition
[[ 2  4  6]
 [ 8 10 12]]
Subtraction
[[0 0 0]
 [0 0 0]]
Multiplication
[[ 1  4  9]
 [16 25 36]]
