In [1]:
import numpy as np
m=np.matrix([[1,2,3],[4,5,6]])
print(m)
print("T")
print(np.transpose(m))
print()
print(m.T)
print("swapaxes")
print(np.swapaxes(m,0,1))

[[1 2 3]
 [4 5 6]]
T
[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]
swapaxes
[[1 4]
 [2 5]
 [3 6]]


In [2]:
m2=np.matrix([[1,2],[4,5]])
print(np.swapaxes(m2,0,1))

[[1 4]
 [2 5]]


In [3]:
m3=np.matrix([[1,2],[3,3]])
print(np.linalg.inv(m3))

[[-1.          0.66666667]
 [ 1.         -0.33333333]]


**power**

In [7]:
m4=np.matrix([[1,2],[3,4]])
print("power<0")
print(np.linalg.matrix_power(m4,-3))
print("power=0")
print(np.linalg.matrix_power(m4,0))
print("power>0")
print(np.linalg.matrix_power(m4,4))

[[-14.75    6.75 ]
 [ 10.125  -4.625]]
[[1 0]
 [0 1]]
[[199 290]
 [435 634]]


**Deteminate**

In [10]:
m5=np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(np.linalg.det(m5))

0.0
